<?php
add_action('init', function () {
  register_post_type('product', array(
    'labels' => array(
      'name' => 'Products',
      'singular_name' => 'Product',
      'menu_name' => 'Products',
      'all_items' => 'All Products',
      'edit_item' => 'Edit Product',
      'view_item' => 'View Product',
      'view_items' => 'View Products',
      'add_new_item' => 'Add New Product',
      'add_new' => 'Add New Product',
      'new_item' => 'New Product',
      'parent_item_colon' => 'Parent Product:',
      'search_items' => 'Search Products',
      'not_found' => 'No products found',
      'not_found_in_trash' => 'No products found in Trash',
      'archives' => 'Product Archives',
      'attributes' => 'Product Attributes',
      'insert_into_item' => 'Insert into product',
      'uploaded_to_this_item' => 'Uploaded to this product',
      'filter_items_list' => 'Filter products list',
      'filter_by_date' => 'Filter products by date',
      'items_list_navigation' => 'Products list navigation',
      'items_list' => 'Products list',
      'item_published' => 'Product published.',
      'item_published_privately' => 'Product published privately.',
      'item_reverted_to_draft' => 'Product reverted to draft.',
      'item_scheduled' => 'Product scheduled.',
      'item_updated' => 'Product updated.',
      'item_link' => 'Product Link',
      'item_link_description' => 'A link to a product.',
    ),
    'public' => true,
    'hierarchical' => true,
    'show_in_rest' => true,
    'supports' => array(
      0 => 'title',
      1 => 'editor',
      2 => 'page-attributes',
      3 => 'thumbnail',
      4 => 'custom-fields',
      5 => '_is_featured',
    ),
    'has_archive' => 'products',
    'delete_with_user' => false,
  ));
});
