name: Deploy to Production

on:
  push:
    branches:
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Production Server via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_USER }}
          password: ${{ secrets.PROD_PASSWORD }}
          port: ${{ secrets.PROD_PORT }} # Optional: default is 22 if not provided
          script: |
            cd domains/dimgrey-wombat-685059.hostingersite.com/public_html/wp-content/themes/my-theme-child/
            git checkout production
            git pull origin production
            export PATH=$HOME/node/bin:$PATH
            echo 'export PATH=$HOME/node/bin:$PATH' >> ~/.bashrc
            npm install
            npm run build
            # Optionally add any build or cache-clear commands here
